app/urls.py
from app import views
from django.conf.urls import url
from django.urls import path

# from django.conf import settings
# from django.conf.urls.static import static

app_name = 'app'

urlpatterns = [
    url(r'^$', views.summary, name='index'),
    url('^summary/$', views.summary, name="summary"),

    url('^settings/main$', views.main_tab, name="main_settings"),
    url('^settings/bank$', views.bank_tab, name="bank_settings"),
    url('^settings/agent$', views.agent, name="agent_settings"),

    url(r'^download/$', views.download_file, name='download_file'),

    url('^result/$', views.isk_tmp_first, name="result_multiform"),
    url('^getsud/$', views.get_sudrf),

    # url('^findcourt/$', views.find_court_for_first_tmp),
    url('^updatecourt/$', views.get_court),
    url('^updcourtmoscowregion/$', views.get_courts_moscow_region),

    #####
    path('isk_tmp/1', views.isk_tmp_first, name='isk_tmp'),
    path('isk_tmp/2', views.isk_tmp_second, name='isk_tmp_2'),
    path('debtors_list', views.debtors_list, name='debtors_list'),
    path('debtors_list_2', views.debtors_list_2, name='debtors_list_2'),
    path('preisk_tmp', views.pretrial_tmp, name='pretrial_tmp'),
    path('history_tmp', views.history_tmp, name='history_tmp'),

    path('get-debit-land/<member_id>', views.get_debit_land),
    path('findcourt', views.find_court_for_first_tmp),
    path('findcourtmir', views.find_court_for_second_tmp),
    path('issued', views.issued),


    path('protocol', views.protocol_list, name='protocol_list'),
    path('protocol/add', views.protocol_create, name='protocol_add'),
    path('protocol/<id>/edit', views.protocol_update, name='protocol_edit'),

    path('member', views.member_list, name='member_list'),
    # path('member/add', views.member_create, name='member_add'),
    path('member/add', views.member_add, name='member_add'),
    path('member/get', views.members_get),
    path('member/<id>/edit', views.member_update, name='member_edit'),
    # path('member/<id>/detail', views.member_detail, name='member_detail'),
    path('member/<id>', views.member_detail, name='member_detail'),
    path('member/land', views.get_land_for_member, name='member_land'),
    path('member/<id>/get', views.member_get),
    path('member/<id>/del', views.member_del),

    path('debt', views.debit_list, name='debit_list'),
    path('debt/<member_id>', views.debit_detail, name='debit_detail'),
    path('debit/add', views.debit_add, name='debit_add'),
    path('debit/<id>/del', views.debit_del, name='debit_del'),
    path('debitgroup/<member_id>/del', views.debitgroup_del, name='debitgroup_del'),
    path('debit/<id>/get', views.debit_get, name='debit_get'),
    path('debit/<id>/edit', views.debit_edit, name='debit_edit'),
    path('debit/<id>/list', views.debit_get_list, name='debit_get_list'),

    # path('debit/detail', views.debit_list, name='debit_list'),          # Подробная информация по списку

    path('payment', views.payment_list, name='payment_list'),
    path('payment/add', views.payment_add, name='payment_add'),
    path('payment/<id>/get', views.payment_get, name='payment_get'),
    path('payment/<id>/del', views.payment_del, name='payment_del'),
    path('payment-group/<id_land>/get', views.get_payment_for_land),
    path('payment-group/<id_land>/del', views.del_payment_for_land),


    # path('land/<id>/add', views.land_create, name='land_add'),
    path('land/<id>/edit', views.land_update, name='land_edit'),
    path('land/add', views.land_add, name='land_add'),
    path('land/get', views.get_lands),
    path('land/<id>/get', views.get_land),
    # path('land/<instruction>/<pk>', views.change_land, name='change_land'),
    path('land/<id>/del', views.land_delete),

    path('ownership/<id>/get', views.get_ownership),
    path('ownership/<id>/edit', views.edit_ownership),
    path('ownership/<id>/del', views.del_ownership),

    path('inn', views.find_inn),
    path('bik', views.find_bik),
    path('company', views.company_detail, name='company_detail'),
    path('bank', views.company_detail, name='company_bank'),
    path('agent', views.company_detail, name='company_agent'),
    path('scan', views.company_detail, name='company_scan'),
    path('company/add', views.company_create, name='company_add'),
    path('company/edit', views.company_update, name='company_edit'),

    # path('bank', views.bank_detail, name='bank_detail'),
    path('bank/add', views.bank_create, name='bank_add'),
    path('bank/<id>/edit', views.bank_update, name='bank_edit'),

    # path('agent', views.agent_list, name='agent_list'),
    path('agent/add', views.agent_create, name='agent_add'),
    path('agent/<id>/edit', views.agent_update, name='agent_edit'),

    path('getkeyrate', views.get_key_rate, name='get_key_rate'),

    path('lands', views.lands, name='lands'),
    path('penalties', views.penalties, name='penalties'),
    path('penalties/<id>/get', views.get_penalty),
    path('penalties/<id>/del', views.del_penalty),

    path('fee', views.members_fee, name='members_fee'),
    path('fee/add', views.members_fee_create, name='members_fee_create'),
    path('fee/<id>/get', views.get_members_fee),
    path('fee/<id>/del', views.del_members_fee),

    path('about', views.about, name='about'),
    path('doc-penalty', views.doc_penalty, name='doc_penalty'),

    path('testmember', views.test_member, name='test_member'),
    path('testlands', views.test_land, name='test_land'),

    path('test', views.test_index, name='test_index'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templater/urls.py
from django.contrib import admin
from django.urls import path, include

# использование статических файлов
from django.conf import settings
from django.conf.urls.static import static

# перенаплавние запросов с корневого URL
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/', include('landing.urls')),
    path('accounts/', include('accounts.urls')),
    path('app/', include('app.urls')),
    path('', RedirectView.as_view(url='/site/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from datetime import timedelta

from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Row, Column, Submit, Field, ButtonHolder, Button, Fieldset, HTML, Hidden
from crispy_forms.bootstrap import FormActions, PrependedText, FieldWithButtons, StrictButton
from app.models import *


class JudicialTmpForm(forms.Form):
    """
        Шаблон для мульти-формы "Исковое заявление".
        С его помощью я формирую конечный документ.
    """
    org_name = forms.CharField(label='Наименование СНТ', max_length=100, )
    org_inn = forms.CharField(label='ИНН СНТ', max_length=50, )
    org_ogrn = forms.CharField(label='ОГРН СНТ', max_length=50, )
    org_full_address = forms.CharField(label='Адрес СНТ', max_length=100, )

    # Представитель
    agent_name = forms.CharField(label='Представитель СНТ', max_length=50, )
    agent_address = forms.CharField(label='Адрес представителя СНТ', max_length=50, )
    agent_phone = forms.CharField(label='Телефон представителя СНТ', max_length=50, )

    # Банковские реквизиты
    # bank_name = forms.CharField(max_length=100, label='Наименование банка',)
    # bank_bik = forms.CharField(max_length=100, label='БИК',)
    # bank_inn = forms.CharField(max_length=100, label='ИНН',)
    # bank_kpp = forms.CharField(max_length=100, label='КПП',)
    # bank_correspondent_acc = forms.CharField(max_length=100, label='Корреспондетский счет',)


class PretrialTmpForm(forms.Form):
    """
        Шаблон для Мульти-формы "Досудебная претензия"
        С его помощью формируем готовый документ
    """
    member_name = forms.CharField(label='ФИО должника', max_length=100, )
    address_land = forms.CharField(label='Адрес земельного участка', max_length=100, )
    num_land = forms.CharField(label='Номер земельного участка', max_length=10, )
    cadastr_num = forms.CharField(label='Кадастровый номер', max_length=30, )

    # Задолженность
    amount_debt = forms.CharField(label='Сумма задолженности', max_length=15, )
    start_debt = forms.CharField(label='Начало задолжености', max_length=15, )
    end_debt = forms.CharField(label='Конец задолженности', max_length=15, )

    # company_name = forms.CharField(label='Наименование СНТ', max_length=50,)
    # fio_manager = forms.CharField(label='Председатель', max_length=50,)
    # company_contact = forms.CharField(label='Контакты', max_length=50,)

    # Протокол собрания
    protocol_create = forms.CharField(label='Дата принятия протокола', max_length=15, )
    protocol_period = forms.CharField(label='Период протокола', max_length=15, )
    protocol_renta = forms.CharField(label='Сумма взносов(меся)', max_length=15, )

    # Банковские реквизиты
    # bank_name = forms.CharField(label='Наименование банка', max_length=100,)
    # bank_bik = forms.CharField(label='БИК', max_length=100,)
    # bank_inn = forms.CharField(label='ИНН', max_length=100,)
    # bank_kpp = forms.CharField(label='КПП', max_length=100,)
    # bank_ogrn = forms.CharField(label='ОГРН', max_length=100,)
    # bank_correspondent_acc = forms.CharField(label='Корреспондетский счет', max_length=100,)
    # bank_payment_acc = forms.CharField(label='Расчетный счет', max_length=100,)Co


class MemberForm(forms.ModelForm):
    """
        Член товарищества
    """
    first_name = forms.CharField(
        label='Имя: ',
        max_length=40,
        # widget=forms.TextInput(attrs={'placeholder': 'Имя'})
    )
    second_name = forms.CharField(
        label='Фамилия: ',
        max_length=40,
        # widget=forms.TextInput(attrs={'placeholder': 'Фамилия'})
    )
    third_name = forms.CharField(
        label='Отчество: ',
        max_length=40,
        # widget=forms.TextInput(attrs={'placeholder': 'Отчество'})
    )
    phone = forms.CharField(
        label='Номер телефона: ',
        max_length=18,
        widget=forms.TextInput(attrs={'data-mask': '+7 (000) 000-00-00',
                                      'placeholder': '+7 (000) 000-00-00'}),
        required=False
    )
    email = forms.CharField(
        label='Электронная почта: ',
        max_length=50,
        required=False
    )
    status = forms.CharField(
        label='Статус',
        max_length=1,
        widget=forms.Select(choices=MemberModel.CHOICE_STATUS),
        initial='1'
    )

    address = forms.CharField(
        label='Адрес регистрации: ',
        max_length=100
    )

    issued = forms.CharField(
        label='Кем выдан: ',
        required=False,
        widget=forms.Textarea(
            attrs={
                'rows': 2, 'cols': 20,
            }
        )
    )

    date_of_issue = forms.DateField(
        label='Дата выдачи: ',
        input_formats=['%d.%m.%Y'],
        required=False
    )

    division_code = forms.CharField(
        label='Код подразделения: ',
        max_length=7,
        widget=forms.TextInput(attrs={'data-mask': '000-000',
                                      'placeholder': '000-000'}),
        required=False
    )

    series_number_doc = forms.CharField(
        label='Серия и номер паспорта: ',
        max_length=15,
        widget=forms.TextInput(attrs={'data-mask': '00 00 № 000000',
                                      'placeholder': '00 00 № 000000'}),
        required=False
    )

    date_of_birth = forms.DateField(
        label='Дата рождения: ',
        input_formats=['%d.%m.%Y'],
        required=False
    )

    place_of_birth = forms.CharField(
        label='Место рождения: ',
        max_length=100,
        required=False
    )

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.layout = Layout(
        Div(
            Div('second_name', css_class='col'),
            Div('first_name', css_class='col'),
            css_class='row'
        ),
        Div(
            Div('third_name', css_class='col'),
            Div('status', css_class='col'),
            css_class='row'
        ),
        Div('address'),
        Div('series_number_doc'),
        Div(
            Div('division_code', css_class='col'),
            Div('date_of_issue', css_class='col'),
            css_class='row'
        ),
        Div('issued'),
        Div(
            Div('date_of_birth', css_class='col'),
            Div('place_of_birth', css_class='col'),
            css_class='row'
        ),
        Div(
            Div('phone', css_class='col'),
            Div('email', css_class='col'),
            css_class='row'
        )
    )

    class Meta:
        model = MemberModel
        fields = ['first_name', 'second_name', 'third_name', 'email', 'phone', 'address',
                  'series_number_doc', 'division_code', 'date_of_issue', 'issued', 'date_of_birth', 'place_of_birth',
                  'status', 'id']


class OwnershipForm(forms.ModelForm):
    start_hold = forms.DateField(
        label='C даты: ',
        input_formats=['%d.%m.%Y'],
        widget=forms.TextInput(
            attrs={
                # 'class': 'form-control-sm',
            }
        )
    )

    end_hold = forms.DateField(
        label='По дату: ',
        input_formats=['%d.%m.%Y'],
        widget=forms.TextInput(
            attrs={
                # 'class': 'form-control-sm',
            }
        )
    )

    comment = forms.CharField(
        label='Комментарий: ',
        required=False,
        widget=forms.Textarea(
            attrs={
                'rows': 2, 'cols': 20,
                # 'class': 'form-control-sm',
            }
        )
    )

    attachment = forms.FileField(
        label='Приложение: ',
        required=False,

        widget=forms.FileInput(
            attrs={
                'accept': 'application/pdf',
                # 'class': 'form-control-sm',
            }

        )
    )

    helper = FormHelper()
    helper.form_method = 'POST'
    helper.layout = Layout(
        Row(
            Column('start_hold'),
            Column('end_hold'),
        ),
        Field('attachment'),
        Field('comment'),
    )

    class Meta:
        model = OwnershipModel
        fields = ['start_hold', 'end_hold', 'comment', 'attachment']


class CreditForm(forms.ModelForm):
    date_start = forms.DateField(
        label='Начало задолженности',
        input_formats=['%d.%m.%Y'],
    )
    date_finish = forms.DateField(
        label='Конец задолженности',
        input_formats=['%d.%m.%Y'],
    )
    summa = forms.FloatField(label='Сумма задолженности')

    class Meta:
        model = Credits
        fields = ['date_start', 'date_finish', 'summa', 'land_id', 'meeting_id']


class LandsForm(forms.ModelForm):
    number = forms.CharField(
        label='Номер участка: ',
        max_length=10,
        widget=forms.TextInput(
            attrs={
                # 'class': 'form-control-sm',
            }
        )
    )
    kadastr_number = forms.CharField(
        label='Кадастровый номер: ',
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'data-mask': '00:00:0000000:0000',
                'placeholder': 'XX:XX:ХХХХХХХ:ХХХХ',
                # 'class': 'form-control-sm',
            }),
    )
    land_address = forms.CharField(
        label='Адрес участка: ',
        max_length=150,
        widget=forms.TextInput(
            attrs={
                # 'class': 'form-control-sm',
            }
        )
    )

    comment = forms.CharField(
        label='Комментарий: ',
        required=False,
        widget=forms.Textarea(
            attrs={
                'rows': 2, 'cols': 20,
                # 'class': 'form-control-sm',
            }
        )
    )

    attachment = forms.FileField(
        label='Приложение: ',
        required=False,
        widget=forms.FileInput(
            attrs={
                'accept': 'application/pdf',
                # 'class': 'form-control-sm ',
            }
        )
    )

    helper = FormHelper()
    helper.form_method = 'POST'
    # helper.label_class = 'form-control-sm m-0 p-0'
    helper.layout = Layout(

app/templates/settings/agent.html
{% extends "base_generic.html" %}

{% block content %}
{% load crispy_forms_tags %}
    <div class="container">
        <h3>Организация</h3>
        <ul class="nav nav-tabs pt-3">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'app:company_detail'%}">Основные</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'app:bank_detail'%}">Банковские реквизиты</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'app:agent_list' %}">Представители</a>
          </li>
        </ul>

    {% if err_msg %}
        <p align="center">{{ err_msg }}</p>
    {% elif form_agent %}
        <div style="height: 20px;"></div>
        <h5>Добавить представителя компании</h5>
        {% crispy form_agent %}
    {% else %}
        <div style="height: 20px;"></div>
        <h5>Представители компании</h5>
        <table class="table table-hover mt-3 table-sm text-muted table-bordered">
          <thead>
            <tr>
              <th scope="col" style="border-bottom: 0px;">ФИО</th>
              <th scope="col" style="border-bottom: 0px;">Адрес</th>
              <th scope="col" style="border-bottom: 0px;">Телефон</th>
            </tr>
          </thead>
          <tbody>
            {% for data in dataset %}
            <tr style="cursor: pointer" onclick="document.location = '{% url 'app:agent_edit' id=data.id %}';">
                <td>{{ data.fio }}</td>
                <td>{{ data.address }}</td>
                <td>{{ data.phone }}</td>
            </tr>
            {% empty %}
                <tr><td colspan="3" align="center">В базе данных нет информации о Представителях компании</td></tr>
            {% endfor %}
          </tbody>
        </table>
        <a href="{% url 'app:agent_add' %}">
            <button class="btn btn-primary mb-5 pull-right mt-3" type="submit">Добавить</button>
        </a>
    {% endif %}
    </div>
{% endblock %}

app/templates/settings/bank.html
{% extends "base_generic.html" %}

{% block content %}
{% load crispy_forms_tags %}
    <div class="container">
        <h3>Организация</h3>
        <ul class="nav nav-tabs pt-3">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'app:company_detail'%}">Основные</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'app:bank_detail'%}">Банковские реквизиты</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'app:agent_list' %}">Представители</a>
          </li>
        </ul>


    {% if err_msg %}
        <p align="center">{{ err_msg }}</p>
    {% elif form_bank %}
        <div style="height: 20px;"></div>
        <h5>Добавление банковских реквизитов</h5>
        {% crispy form_bik %}
        {% crispy form_bank %}
    {% else %}
        <div style="height: 20px;"></div>
        <h5>Расчетные счета компании</h5>
        <table class="table table-hover mt-3 table-sm text-muted table-bordered">
          <thead>
            <tr>
              <th scope="col" style="border-bottom: 0px;">ID</th>
              <th scope="col" class="w-50" style="border-bottom: 0px;">Расчетный счет</th>
              <th scope="col" class="w-50" style="border-bottom: 0px;">Наименование банка</th>
            </tr>
          </thead>
          <tbody>
            {% for data in dataset %}
            <tr style="cursor: pointer" onclick="document.location = '{% url 'app:bank_edit' id=data.id %}';">
                <td>{{ data.id }}</td>
                <td>{{ data.checking_acc }}</td>
                <td>{{ data.bank_name }}</td>
            </tr>
            {% empty %}
                <tr><td colspan="3" align="center">В базе данных нет информации о Банковских реквизитах</td></tr>
            {%  endfor %}
          </tbody>
        </table>
        <a href="{% url 'app:bank_add' %}">
            <button class="btn btn-primary mb-5 pull-right mt-3" type="submit">Добавить</button>
        </a>
    {% endif %}

    </div>
{% endblock %}

app/templates/settings/member_view.html
{% extends "base_generic.html" %}

{% block content %}

<div class="container">
    <h3>Карточка члена товарищества</h3>
    <div class="row">
        <div class="m-auto col-md-8">
            <dl class="row">
                <dt class="col-sm-3">ФИО:</dt>
                <dd class="col-sm-9">{{ member_detail.fio }}</dd>
                <dt class="col-sm-3">Адрес:</dt>
                <dd class="col-sm-9">{{ member_detail.address }}</dd>
                <dt class="col-sm-3">Телефон:</dt>
                <dd class="col-sm-9">{{ member_detail.phone }}</dd>
                {% if member_detail.status == '1' %}
                    <dt class="col-sm-3">Член товарищества:</dt>
                    <dd class="col-sm-9">Да</dd>
                {% else %}
                    <dt class="col-sm-3">Член товарищества:</dt>
                    <dd class="col-sm-9">Нет</dd>
                {% endif %}
            </dl>
        </div>
        <div class="col-md-4">
            <a href="{% url 'app:member_edit' id=member_detail.id %}">
                <button class="btn btn-primary ml-3 pull-right" type="submit">Редактировать</button>
            </a>
        </div>
    </div>
    <hr/>

    <h4>Участки</h4>
    <table class="table table-hover table-sm text-muted table-bordered">
        <thead>
            <tr>
                <th scope="col" style="border-bottom: 0px; text-align: center;">№</th>
                <th scope="col" style="border-bottom: 0px;">Адрес участка</th>
                <th scope="col" class="w-50" style="border-bottom: 0px;">Кадастровый номер</th>
            </tr>
        </thead>
        <tbody>
            {% for item in lands %}
            <tr style='cursor: pointer;' onclick="document.location = '{% url 'app:land_edit' id=item.id %}';">
                <td align="center">{{ item.number }}</td>
                <td>{{ item.address }}</td>
                <td>{{ item.kadastr_number }}</td>
            </tr>
            {% empty %}
            <tr><td colspan="3" align="center">Нет ни одного участка</td></tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'app:land_add' id=member_detail.id %}">
        <button class="btn btn-primary pull-right" type="submit">Добавить</button>
    </a>

    <div style="height: 50px;"></div>

    <h4>Задолженность</h4>

    <table class="table table-hover table-sm text-muted table-bordered">
      <thead>
        <tr>
          <th scope="col" style="border-bottom: 0px;">Начало задолженности</th>
          <th scope="col" style="border-bottom: 0px;">Конец задолженности</th>
          <th scope="col" class="w-50" style="border-bottom: 0px;">Сумма</th>
        </tr>
      </thead>
      <tbody>
      {% for item in credits %}
        <tr style="cursor: pointer" onclick="document.location = '{% url 'app:credit_edit' id=item.id %}';">
          <td>{{ item.date_start|date:"d.m.Y" }}</td>
          <td>{{ item.date_finish|date:"d.m.Y" }}</td>
          <td>{{ item.summa }}</td>
        </tr>
      {% empty %}
          <tr><td colspan="3" align="center">Нет задолженности</td></tr>
      {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'app:credit_add' id=member_detail.id %}">
    <button class="btn btn-primary mb-5 pull-right" type="submit">Добавить</button>
    </a>

</div>

{% endblock %}

app/templates/settings/protocol.html
{% extends "base_generic.html" %}

{% block styles %}
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
    <div class="container">
    <h3>Протоколы собраний</h3>
    {% if err_msg %}
        <p align="center">{{ err_msg }}</p>
    {% elif form %}
        {% crispy form %}
    {% else %}
        <table class="table table-hover mt-3 table-sm text-muted table-bordered">
            <thead>
            <tr>
                <th scope="col" style="border-bottom: 0px;">№ Протокола</th>
                <th scope="col" style="border-bottom: 0px;">Дата принятия</th>
                <th scope="col" style="border-bottom: 0px;">Окончание</th>
                <th scope="col" style="border-bottom: 0px;">Размер взноса</th>
            </tr>
            </thead>
            <tbody>
            {% for data in dataset %}
            <tr onclick="document.location = '{% url 'app:protocol_edit' id=data.id %}';">
                <td>{{ data.number }}</td>
                <td>{{ data.date_start }}</td>
                <td>{{ data.date_finish }}</td>
                <td>{{ data.renta }}</td>
            </tr>
            {% empty %}
                <tr><td colspan="4" align="center">В базе данных нет Протоколов собрания</td></tr>
            {%  endfor %}
            </tbody>
        </table>
        <a href="{% url 'app:protocol_add' %}">
            <button class="btn btn-primary mb-5 pull-right" type="submit">Добавить</button>
        </a>
    {% endif %}
    </div>
{% endblock %}

{% block scripts %}
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <script>
    /* Локализация datepicker */
    $.datepicker.regional['ru'] = {
        closeText: 'Закрыть',
        prevText: 'Предыдущий',
        nextText: 'Следующий',
        currentText: 'Сегодня',
        monthNames: ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
        monthNamesShort: ['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'],
        dayNames: ['воскресенье','понедельник','вторник','среда','четверг','пятница','суббота'],
        dayNamesShort: ['вск','пнд','втр','срд','чтв','птн','сбт'],
        dayNamesMin: ['Вс','Пн','Вт','Ср','Чт','Пт','Сб'],
        weekHeader: 'Не',
        dateFormat: 'dd.mm.yy',
        firstDay: 1,
        isRTL: false,
        showMonthAfterYear: false,
        yearSuffix: ''
    };
    $.datepicker.setDefaults($.datepicker.regional['ru']);

    $(document).ready(function() {
        $('#id_date_start').datepicker({ dateFormat: 'dd.mm.yy' });
        $('#id_date_finish').datepicker({ dateFormat: 'dd.mm.yy' });
    });
    </script>
{% endblock %}