app/urls.py
from app import views
from django.conf.urls import url
from django.urls import path

# from django.conf import settings
# from django.conf.urls.static import static

app_name = 'app'

urlpatterns = [
    url(r'^$', views.summary, name='index'),
    url('^summary/$', views.summary, name="summary"),

    url('^settings/main$', views.main_tab, name="main_settings"),
    url('^settings/bank$', views.bank_tab, name="bank_settings"),
    url('^settings/agent$', views.agent, name="agent_settings"),

    url(r'^download/$', views.download_file, name='download_file'),

    url('^result/$', views.isk_tmp_first, name="result_multiform"),
    url('^getsud/$', views.get_sudrf),

    # url('^findcourt/$', views.find_court_for_first_tmp),
    url('^updatecourt/$', views.get_court),
    url('^updcourtmoscowregion/$', views.get_courts_moscow_region),

    #####
    path('isk_tmp/1', views.isk_tmp_first, name='isk_tmp'),
    path('isk_tmp/2', views.isk_tmp_second, name='isk_tmp_2'),
    path('debtors_list', views.debtors_list, name='debtors_list'),
    path('debtors_list_2', views.debtors_list_2, name='debtors_list_2'),
    path('preisk_tmp', views.pretrial_tmp, name='pretrial_tmp'),
    path('history_tmp', views.history_tmp, name='history_tmp'),

    path('get-debit-land/<member_id>', views.get_debit_land),
    path('findcourt', views.find_court_for_first_tmp),
    path('findcourtmir', views.find_court_for_second_tmp),
    path('issued', views.issued),


    path('protocol', views.protocol_list, name='protocol_list'),
    path('protocol/add', views.protocol_create, name='protocol_add'),
    path('protocol/<id>/edit', views.protocol_update, name='protocol_edit'),

    path('member', views.member_list, name='member_list'),
    # path('member/add', views.member_create, name='member_add'),
    path('member/add', views.member_add, name='member_add'),
    path('member/get', views.members_get),
    path('member/<id>/edit', views.member_update, name='member_edit'),
    # path('member/<id>/detail', views.member_detail, name='member_detail'),
    path('member/<id>', views.member_detail, name='member_detail'),
    path('member/land', views.get_land_for_member, name='member_land'),
    path('member/<id>/get', views.member_get),
    path('member/<id>/del', views.member_del),

    path('debt', views.debit_list, name='debit_list'),
    path('debt/<member_id>', views.debit_detail, name='debit_detail'),
    path('debit/add', views.debit_add, name='debit_add'),
    path('debit/<id>/del', views.debit_del, name='debit_del'),
    path('debitgroup/<member_id>/del', views.debitgroup_del, name='debitgroup_del'),
    path('debit/<id>/get', views.debit_get, name='debit_get'),
    path('debit/<id>/edit', views.debit_edit, name='debit_edit'),
    path('debit/<id>/list', views.debit_get_list, name='debit_get_list'),

    # path('debit/detail', views.debit_list, name='debit_list'),          # Подробная информация по списку

    path('payment', views.payment_list, name='payment_list'),
    path('payment/add', views.payment_add, name='payment_add'),
    path('payment/<id>/get', views.payment_get, name='payment_get'),
    path('payment/<id>/del', views.payment_del, name='payment_del'),
    path('payment-group/<id_land>/get', views.get_payment_for_land),
    path('payment-group/<id_land>/del', views.del_payment_for_land),


    # path('land/<id>/add', views.land_create, name='land_add'),
    path('land/<id>/edit', views.land_update, name='land_edit'),
    path('land/add', views.land_add, name='land_add'),
    path('land/get', views.get_lands),
    path('land/<id>/get', views.get_land),
    # path('land/<instruction>/<pk>', views.change_land, name='change_land'),
    path('land/<id>/del', views.land_delete),

    path('ownership/<id>/get', views.get_ownership),
    path('ownership/<id>/edit', views.edit_ownership),
    path('ownership/<id>/del', views.del_ownership),

    path('inn', views.find_inn),
    path('bik', views.find_bik),
    path('company', views.company_detail, name='company_detail'),
    path('bank', views.company_detail, name='company_bank'),
    path('agent', views.company_detail, name='company_agent'),
    path('scan', views.company_detail, name='company_scan'),
    path('company/add', views.company_create, name='company_add'),
    path('company/edit', views.company_update, name='company_edit'),

    # path('bank', views.bank_detail, name='bank_detail'),
    path('bank/add', views.bank_create, name='bank_add'),
    path('bank/<id>/edit', views.bank_update, name='bank_edit'),

    # path('agent', views.agent_list, name='agent_list'),
    path('agent/add', views.agent_create, name='agent_add'),
    path('agent/<id>/edit', views.agent_update, name='agent_edit'),

    path('getkeyrate', views.get_key_rate, name='get_key_rate'),

    path('lands', views.lands, name='lands'),
    path('penalties', views.penalties, name='penalties'),
    path('penalties/<id>/get', views.get_penalty),
    path('penalties/<id>/del', views.del_penalty),

    path('fee', views.members_fee, name='members_fee'),
    path('fee/add', views.members_fee_create, name='members_fee_create'),
    path('fee/<id>/get', views.get_members_fee),
    path('fee/<id>/del', views.del_members_fee),

    path('about', views.about, name='about'),
    path('doc-penalty', views.doc_penalty, name='doc_penalty'),

    path('testmember', views.test_member, name='test_member'),
    path('testlands', views.test_land, name='test_land'),

    path('test', views.test_index, name='test_index'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templater/urls.py
from django.contrib import admin
from django.urls import path, include

# использование статических файлов
from django.conf import settings
from django.conf.urls.static import static

# перенаплавние запросов с корневого URL
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/', include('landing.urls')),
    path('accounts/', include('accounts.urls')),
    path('app/', include('app.urls')),
    path('', RedirectView.as_view(url='/site/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.gis.db import models
from django.contrib.auth.models import User
from datetime import datetime
import os


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    # return 'user_{0}/{1}'.format(instance.company.id, filename)
    return os.path.join(str(instance.company_id_id), filename)


class CompanyModel(models.Model):
    company_name = models.CharField(max_length=100)
    company_inn = models.CharField(max_length=10)
    company_ogrn = models.CharField(max_length=13)
    full_company_name = models.CharField(max_length=100)
    fio_manager = models.CharField(max_length=100)
    position_manager = models.CharField(max_length=50)
    full_address = models.CharField(max_length=100)
    phone = models.CharField(max_length=18)
    email = models.EmailField(max_length=50)
    user_snt = models.OneToOneField(User, on_delete=models.CASCADE)
    # penalty_id = models.ForeignKey(PenaltyModel, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.company_name

    class Meta:
        verbose_name = 'СНТ'
        verbose_name_plural = 'СНТ'


class PenaltyModel(models.Model):
    description = models.CharField(max_length=100)
    date_start = models.DateField(unique=True, null=True)
    attachment = models.FileField(upload_to=user_directory_path, blank=True)
    rate = models.FloatField()
    company_id = models.ForeignKey(CompanyModel, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.description

    class Meta:
        verbose_name = 'Начисления'
        verbose_name_plural = 'Начисления'


class BankModel(models.Model):
    bank_name = models.CharField(max_length=70)
    bik_bank = models.CharField(max_length=9)
    inn_bank = models.CharField(max_length=10)
    kpp = models.CharField(max_length=9)
    correspondent_acc = models.CharField(max_length=20)
    checking_acc = models.CharField(max_length=20)
    company_id = models.ForeignKey(CompanyModel, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.bank_name

    class Meta:
        verbose_name = 'Банковские реквизиты'
        verbose_name_plural = 'Банковские реквизиты'


class AgentModel(models.Model):
    CHOICE_DOC = (
        ('0', 'Доверенность'),
        ('1', 'Протокол'),
    )
    first_name = models.CharField(max_length=20)
    second_name = models.CharField(max_length=20)
    third_name = models.CharField(max_length=20)
    position = models.CharField(max_length=50)
    phone = models.CharField(max_length=18, blank=True)
    address = models.CharField(max_length=70, blank=True)
    doc = models.CharField(max_length=1, choices=CHOICE_DOC, default='1')
    num_doc = models.CharField(max_length=15, blank=True)
    date_doc = models.DateField(null=True)
    file_doc = models.FileField(upload_to=user_directory_path, blank=True)
    active = models.BooleanField(null=True, default=False)
    company_id = models.ForeignKey(CompanyModel, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.second_name

    class Meta:
        verbose_name = 'Председатель'
        verbose_name_plural = 'Председатели'


class MembersFeeModel(models.Model):
    CHOICE_TYPE = (
        # ('0', '---'),
        ('0', 'Членский взнос'),
        ('1', 'Целевой взнос'),
    )
    CHOICE_PAYMENT = (
        ('1', 'Ежемесячные'),
        ('2', 'Ежеквартальные'),
        ('3', 'Ежегодные'),
    )
    num_doc = models.CharField(max_length=50)
    date_doc = models.DateField()
    date_start = models.DateField(blank=True, null=True)
    date_finish = models.DateField(blank=True, null=True)
    type_fee = models.CharField(max_length=1, choices=CHOICE_TYPE, default='0')
    payment_period = models.CharField(max_length=1, choices=CHOICE_PAYMENT, default='1')
    day_accrual = models.CharField(max_length=2)    # день начисления (называться будет как Дата начислени)
    amount_fee = models.FloatField()
    obj_fee = models.CharField(max_length=100)   # цель взноса (остановились на простом текстовом поле)
    attachment = models.FileField(upload_to=user_directory_path, blank=True)
    comment = models.TextField(max_length=150, blank=True)
    company_id = models.ForeignKey(CompanyModel, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Членский взнос'
        verbose_name_plural = 'Членские взносы'


class DebtCharges(models.Model):
    date_payment = models.DateField()
    # sum_payment = models.FloatField()
    id_member_fee = models.ForeignKey(MembersFeeModel, on_delete=models.CASCADE)


class MemberModel(models.Model):
    CHOICE_STATUS = (
        ('0', 'Не член товарищества'),
        ('1', 'Член товарищества'),
    )
    first_name = models.CharField(max_length=40)
    second_name = models.CharField(max_length=40)
    third_name = models.CharField(max_length=40)
    email = models.EmailField(max_length=50, blank=True, null=True)
    phone = models.CharField(
        max_length=18,
        blank=True)
    address = models.CharField(max_length=150)
    status = models.CharField(
        max_length=1,
        choices=CHOICE_STATUS,
        blank=True,
        default='1'
    )
    # Добавление дополнительных полей
    issued = models.CharField(max_length=255, default='')
    date_of_issue = models.DateField(blank=True, null=True, default=datetime.today())
    division_code = models.CharField(max_length=7, default='000-000')
    series_number_doc = models.CharField(max_length=15, default='00 00 № 000000')
    date_of_birth = models.DateField(blank=True, null=True,default=datetime.today())
    place_of_birth = models.CharField(max_length=100, default='')

    company_id = models.ForeignKey(CompanyModel, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Член товарищества'
        verbose_name_plural = 'Члены товарищества'


class LandModel(models.Model):
    number = models.CharField(max_length=10)
    kadastr_number = models.CharField(max_length=30)
    land_address = models.CharField(max_length=150)
    comment = models.TextField(max_length=200, blank=True)
    attachment = models.FileField(upload_to=user_directory_path, blank=True)
    members = models.ManyToManyField(MemberModel, related_name='lands', through='OwnershipModel', blank=True)
    company_id = models.ForeignKey(CompanyModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.land_address

    class Meta:
        verbose_name = 'Земельный участок'
        verbose_name_plural = 'Земельные участки'

    # @classmethod
    # def add_land(cls, current_member, new_land):
    #     new_land.members.add(current_member)
    #
    # @classmethod
    # def del_land(cls, current_member, cancel_land):
    #     cancel_land.members.remove(current_member)


class OwnershipModel(models.Model):
    member = models.ForeignKey(MemberModel, on_delete=models.CASCADE)
    land = models.ForeignKey(LandModel, on_delete=models.CASCADE)
    start_hold = models.DateField(blank=True, null=True)
    end_hold = models.DateField(blank=True, null=True)
    comment = models.TextField(max_length=200, blank=True)
    attachment = models.FileField(upload_to=user_directory_path, blank=True)


class DebtsModel(models.Model):
    CHOICE_ACC = (
        ('0', 'Автоматические начисления'),
        ('1', 'На дату окончания задолженности'),
    )
    CHOICE_DOC = (
        ('0', 'Членский взнос'),
        ('1', 'Целевой взнос'),
    )
    start_debt = models.DateField()
    end_debt = models.DateField(blank=True, null=True)
    type_accuals = models.CharField(max_length=1, choices=CHOICE_ACC, default='0')
    type_doc = models.CharField(max_length=1, choices=CHOICE_DOC, default='0')
    sum = models.FloatField(blank=True, null=True)
    land = models.ForeignKey(LandModel, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.start_debt) + ' - ' + str(self.end_debt)

    class Meta:
        verbose_name = 'Задолженность'
        verbose_name_plural = 'Задолженности'


class PenaltyCalculationModel(models.Model):
    date = models.CharField(max_length=30)
    date_start = models.DateField()
    date_finish = models.DateField()
    rate = models.FloatField()
    type = models.CharField(max_length=1)
    days = models.IntegerField()
    sum = models.FloatField()
    sum_edit = models.IntegerField()
    debt = models.ForeignKey(DebtsModel, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Калькуляция пени'
        verbose_name_plural = 'Калькуляций пени'


class AccrualsCalculationModel(models.Model):
    date_start = models.DateField()
    date_finish = models.DateField()
    type = models.CharField(max_length=20)
    type_num = models.CharField(max_length=1)
    sum = models.FloatField()
    sum_edit = models.IntegerField()
    debt = models.ForeignKey(DebtsModel, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Калькуляция начислений'
        verbose_name_plural = 'Калькуляций начислений'


class PaymentsModel(models.Model):
    CHOICE_DOC = (
        ('0', 'Членский взнос'),
        ('1', 'Целевой взнос'),
    )
    fio = models.CharField(max_length=100)
    date_payment = models.DateField()
    type_payment = models.CharField(max_length=1, choices=CHOICE_DOC, default='0')
    sum_payment = models.FloatField()
    comment = models.TextField(max_length=200, blank=True)
    land = models.ForeignKey(LandModel, on_delete=models.CASCADE)

    def __str__(self):
        return self.fio + ' - ' + str(self.sum_payment)

    class Meta:
        verbose_name = 'Платеж'
        verbose_name_plural = 'Платежи'


class ScanCompanyModel(models.Model):
    ustav = models.FileField(upload_to=user_directory_path, blank=True)
    ogrn = models.FileField(upload_to=user_directory_path, blank=True)
    inn = models.FileField(upload_to=user_directory_path, blank=True)
    yegryul = models.FileField(upload_to=user_directory_path, blank=True)

app/templates/about.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="d-block w-100 pr-5 pl-5 pb-5 pt-0">
        <h3>{{ data }}</h3>
    </div>
{% endblock %}

app/templates/base_generic.html
<!doctype html>
<html lang="en">
  <head>
		{% block title %}<title>Templater | Личный кабинет пользователя</title>{% endblock %}
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet"/>
		<script src="https://kit.fontawesome.com/fdfa5f9f42.js" crossorigin="anonymous"></script>

		<!-- Добавление дополнительного статического CSS файла -->
		{% load static %}
		<link rel="stylesheet" href="{% static 'app/css/style.css' %}">
{#		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"#}
{#					integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}
		{% block styles %}{% endblock %}

  </head>
  <body>
		<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar">
				<div class="logo">TEMPLATER</div>
				<ul class="components list-unstyled mb-5 p-4">
					<li>
						<a href="{% url 'app:summary' %}" id="submenu1">СВОДКА</a>
					</li>
					<li>
						<a href="#" id="submenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">ВЗЫСКАНИЕ</a>
						<ul class="collapse list-unstyled" id="chapter1">
							<li><a href="{% url 'app:debtors_list' %}">Досудебное взыскание</a></li>
							<li><a href="{% url 'app:debtors_list_2' %}">Судебное взыскание</a></li>
							<li><a href="{% url 'app:history_tmp' %}">История документов</a></li>
							<li><a href="{% url 'app:doc_penalty' %}">Справка по расчету пеней</a></li>
						</ul>
					</li>
					<li>
						<a href="#" id="submenu3" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">РЕЕСТРЫ</a>
						<ul class="collapse list-unstyled" id="chapter2">
							<li><a href="{% url 'app:member_list' %}">Физические лица</a></li>
							<li><a href="{% url 'app:lands' %}">Участки</a></li>
							<li><a href="{% url 'app:debit_list' %}">Задолженности</a></li>
							<li><a href="{% url 'app:payment_list' %}">Платежи</a></li>
						</ul>
					</li>
					<li>
						<a href="#" id="submenu4" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">НАСТРОЙКИ</a>
						<ul class="collapse list-unstyled" id="chapter3">
							<li><a href="{% url 'app:company_detail' %}">Организация</a></li>
							<li><a href="{% url 'app:penalties' %}">Размер неустойки</a></li>
							<li><a href="{% url 'app:members_fee' %}">Членские взносы</a></li>
							<li><a href="{% url 'app:about' %}">О системе</a></li>
						</ul>
					</li>
				</ul>

				<div class="">
					<div class="footer"></div>
				</div>

			</nav>
			<div id="content">
				<nav class="navbar navbar-expand-lg navbar-light bg-light">
					<div class="container-fluid">
						<button type="button" id="sidebarCollapse" class="btn btn-primary">
							<i class="fa fa-bars"></i>
							<span class="sr-only">Toggle Menu</span>
						</button>

						<div class="input-group col-md-6 ml-2">
	{#                    <!-- type="search" -->#}
								<input class="form-control border-right-0 border" value="Поиск должников" id="example-search-input">
								<span class="input-group-append">
									<button class="btn btn-outline-secondary border-left-0 border" type="button">
												<i class="fas fa-search"></i>
									</button>
								</span>
						</div>
						<div class="input-group w-100">
						</div>
						<div class="mr-3">
								<span style="font-size: 24px; color: #00BFA6;">
										<i class="fas fa-question-circle"></i>
								</span>
						</div>
						<div class="mr-3">
								<span style="font-size: 24px; color: #00BFA6;">
										<i class="fas fa-user-cog"></i>
								</span>
						</div>
							{% if user.is_authenticated %}
										<a class="nav-link" href="{% url 'logout'%}?next=/site/">{{ user.username }}</a>
								{% endif %}
					</div>
				</nav>
				{% block content %}{% endblock %}

			</div>
		</div>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		{% block scripts %}{% endblock %}
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>

		<script src="{% static 'app/js/base.js' %}"></script>
  </body>
</html>

app/templates/doc-penalty.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="d-block w-100 pr-5 pl-5 pb-5 pt-0">
        <h3>{{ data }}</h3>
    </div>
{% endblock %}

app/templates/form.html
{% extends "base_generic.html" %}

{% block content %}

	<h3>Шаблон номер 1</h3>
	<br>
	<form method="post" action="/create/" class="form-group">
		{% csrf_token %}
		<div class="input-group mb-3">
	  		<div class="input-group-prepend">
	  		<button name="save" type="submit" class="btn btn-success">Create</button>
	  		</div>
	  		{{form.name}}
		</div>
	</form>

{% endblock %}

app/templates/index.html
{% extends "base_generic.html" %}

{% block content %}

    <div class="container p-5">
        <h2>Основная страница личного кабинета пользователя</h2>
        <p>
            Слева расположены ссылки на шаблоны документов, которые может сформировать приложение
        </p>

    </div>

{% endblock %}

app/templates/land.html
{% extends "base_generic.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h3>Добавить участок</h3>
    {% crispy form %}
</div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'app/multi-form/js/ahunter_suggest.js' %}"></script>
    <script>
      //готовим настройки модуля
      var options = {
        id:'id_address',
      };
      //запускаем модуль подсказок
      AhunterSuggest.Address.Solid(options);
    </script>
{% endblock %}

app/templates/result.html
{% extends "base_generic.html" %}

{% block content %}

    <div class="container p-5">
        <h3>Исковое заявления (Результат запроса)</h3>
        <p>
            Результат отработки Мультиформы
        </p>

        <p>{{ body }}</p>
    </div>

{% endblock %}

app/templates/summary.html
{% extends "base_generic.html" %}

{% block content %}
		<div class="d-block w-100 pr-5 pl-5 pb-5 pt-0">
    <h3>Сводка</h3>
    <div class="row equal">
        <div class="card m-3 h-50" style="width: 25rem;">
          <h5 class="card-header">Количество должников</h5>
          <div class="card-body text-center">
            <p class="card-text font-weight-bold display-4">{{ debtors.count }}</p>
          </div>
        </div>

        <div class="card m-3 h-50" style="width: 25rem;">
          <h5 class="card-header">Количество участков</h5>
          <div class="card-body text-center">
            <p class="card-text font-weight-bold display-4">{{ lands.count }}</p>
          </div>
        </div>

        <div class="card m-3 h-50" style="width: 25rem;">
          <h5 class="card-header">Сумма задолженностей</h5>
          <div class="card-body text-center">
            <p class="card-text font-weight-bold display-4">{{ amount_debt }}</p>
          </div>
        </div>

        <div class="card m-3 h-50" style="width: 25rem;">
          <h5 class="card-header">Претензии</h5>
          <div class="card-body text-center">
            <p class="card-text font-weight-bold display-4">{{ pretrial.count }}</p>
          </div>
        </div>

        <div class="card m-3 h-50" style="width: 25rem;">
          <h5 class="card-header">Исковые зявления</h5>
          <div class="card-body text-center">
            <p class="card-text font-weight-bold display-4">{{ isk1.count }}</p>
          </div>
        </div>

        <div class="card m-3 h-50" style="width: 25rem;">
          <h5 class="card-header">Судебные приказы</h5>
          <div class="card-body text-center">
            <p class="card-text font-weight-bold display-4">{{ isk2.count }}</p>
          </div>
        </div>

{% endblock %}

app/templates/test.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container">
        <h3>Смотри логи в консоле</h3>
    </div>
{% endblock %}